// src/lib/mock-plugins.ts
import { Plugin } from '@/lib/types';

export const mockPlugins: Plugin[] = [
  {
    id: 'amazon',
    name: 'Amazon',
    description: 'Sincronize seus produtos e pedidos com a Amazon Marketplace.',
    category: 'marketplace',
    icon: '🛒',
    status: 'connected',
    enabled: true,
    config: { sellerId: 'A1B2C3D4', region: 'BR' },
    fields: [
      { key: 'sellerId', label: 'Seller ID', type: 'text', placeholder: 'Ex: A1B2C3D4' },
      { key: 'accessKey', label: 'Access Key', type: 'password', placeholder: 'Sua chave de acesso' },
      { key: 'secretKey', label: 'Secret Key', type: 'password', placeholder: 'Sua chave secreta' },
      {
        key: 'region',
        label: 'Região',
        type: 'select',
        options: [
          { value: 'BR', label: 'Brasil' },
          { value: 'US', label: 'Estados Unidos' },
          { value: 'MX', label: 'México' },
        ],
      },
    ],
    lastSync: '2026-03-16T10:30:00Z',
    ordersCount: 142,
  },
  {
    id: 'mercadolivre',
    name: 'Mercado Livre',
    description: 'Gerencie anúncios e estoque diretamente no Mercado Livre.',
    category: 'marketplace',
    icon: '🏪',
    status: 'connected',
    enabled: true,
    config: { userId: 'ML12345678' },
    fields: [
      { key: 'clientId', label: 'Client ID', type: 'text', placeholder: 'ID do aplicativo' },
      { key: 'clientSecret', label: 'Client Secret', type: 'password', placeholder: 'Secret do aplicativo' },
      { key: 'userId', label: 'User ID', type: 'text', placeholder: 'Seu ID de vendedor' },
    ],
    lastSync: '2026-03-16T09:15:00Z',
    ordersCount: 89,
  },
  {
    id: 'shopee',
    name: 'Shopee',
    description: 'Integre produtos e pedidos da Shopee ao seu estoque.',
    category: 'marketplace',
    icon: '🛍️',
    status: 'error',
    enabled: true,
    fields: [
      { key: 'partnerId', label: 'Partner ID', type: 'text', placeholder: 'Seu Partner ID' },
      { key: 'partnerKey', label: 'Partner Key', type: 'password', placeholder: 'Sua Partner Key' },
      { key: 'shopId', label: 'Shop ID', type: 'text', placeholder: 'ID da sua loja' },
    ],
    lastSync: '2026-03-15T22:00:00Z',
    ordersCount: 37,
  },
  {
    id: 'magalu',
    name: 'Magazine Luiza',
    description: 'Conecte-se ao Magalu Marketplace para expandir suas vendas.',
    category: 'marketplace',
    icon: '🏬',
    status: 'disconnected',
    enabled: false,
    fields: [
      { key: 'apiKey', label: 'API Key', type: 'password', placeholder: 'Chave da API Magalu' },
      { key: 'sellerId', label: 'Seller ID', type: 'text', placeholder: 'ID do vendedor' },
    ],
  },
  {
    id: 'tiny',
    name: 'Tiny ERP',
    description: 'Sincronize notas fiscais, pedidos e estoque com o Tiny ERP.',
    category: 'erp',
    icon: '🗂️',
    status: 'connected',
    enabled: true,
    config: { token: '••••••••••••4f2a' },
    fields: [
      { key: 'token', label: 'Token de Acesso', type: 'password', placeholder: 'Token gerado no Tiny' },
    ],
    lastSync: '2026-03-16T08:00:00Z',
  },
  {
    id: 'bling',
    name: 'Bling ERP',
    description: 'Integração com o Bling para emissão de NF-e e controle financeiro.',
    category: 'erp',
    icon: '📒',
    status: 'disconnected',
    enabled: false,
    fields: [
      { key: 'apiKey', label: 'API Key', type: 'password', placeholder: 'Chave de API do Bling' },
    ],
  },
  {
    id: 'correios',
    name: 'Correios',
    description: 'Calcule fretes e rastreie encomendas pelos Correios.',
    category: 'logistics',
    icon: '📦',
    status: 'connected',
    enabled: true,
    config: { contractCode: 'COR-99887' },
    fields: [
      { key: 'contractCode', label: 'Código do Contrato', type: 'text', placeholder: 'Ex: COR-99887' },
      { key: 'user', label: 'Usuário (SIGEP)', type: 'text', placeholder: 'Usuário do sistema' },
      { key: 'password', label: 'Senha (SIGEP)', type: 'password', placeholder: 'Senha do sistema' },
    ],
  },
  {
    id: 'jadlog',
    name: 'Jadlog',
    description: 'Gere etiquetas e acompanhe entregas pela Jadlog.',
    category: 'logistics',
    icon: '🚚',
    status: 'pending',
    enabled: false,
    fields: [
      { key: 'cnpj', label: 'CNPJ', type: 'text', placeholder: 'CNPJ da empresa' },
      { key: 'password', label: 'Senha', type: 'password', placeholder: 'Senha de acesso' },
    ],
  },
  {
    id: 'google-analytics',
    name: 'Google Analytics',
    description: 'Analise o desempenho de vendas com relatórios do Google Analytics.',
    category: 'analytics',
    icon: '📊',
    status: 'disconnected',
    enabled: false,
    fields: [
      { key: 'measurementId', label: 'Measurement ID', type: 'text', placeholder: 'Ex: G-XXXXXXXXXX' },
      { key: 'apiSecret', label: 'API Secret', type: 'password', placeholder: 'Secret da propriedade' },
    ],
  },
  {
    id: 'pagseguro',
    name: 'PagSeguro',
    description: 'Receba pagamentos via PagSeguro integrado ao seu estoque.',
    category: 'payment',
    icon: '💳',
    status: 'disconnected',
    enabled: false,
    fields: [
      { key: 'email', label: 'E-mail da conta', type: 'text', placeholder: 'email@exemplo.com' },
      { key: 'token', label: 'Token', type: 'password', placeholder: 'Token gerado no PagSeguro' },
    ],
  },
];

export const pluginCategoryLabels: Record<string, string> = {
  marketplace: 'Marketplaces',
  erp: 'ERP',
  logistics: 'Logística',
  analytics: 'Analytics',
  payment: 'Pagamentos',
};
